from pygame import USEREVENT
ACTOR_EVENT_START       = USEREVENT + 1
ACTOR_EVENT_END         = USEREVENT + 2
EXIT_EVENT_START        = USEREVENT + 3
EXIT_EVENT_END          = USEREVENT + 4
START_LASER_EVENT       = USEREVENT + 5
END_LASER_EVENT         = USEREVENT + 6
LASER_SEQUENCE          = USEREVENT + 7
TIMER_FLASH_EVENT       = USEREVENT + 8
UNLOCK_EVENT            = USEREVENT + 9
TIMER_LOCK_EVENT        = USEREVENT + 10
LASER_SHOT              = USEREVENT + 11
INTRO_EVENT_START       = USEREVENT + 12
INTRO_EVENT_END       = USEREVENT + 13